spring:
  application:
    name: auth-service

  config:
    activate:
      on-profile: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?characterEncoding=UTF-8&serverTimezone=UTC
    username: doran
    password: doran1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      port: 6379
      host: 127.0.0.1

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate.SQL: debug