server:
  port: 0

spring:
  application:
    name: order-service
  config:
    activate:
      on-profile: dev
  messages:
    basename: errors
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/order-database
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: doran
    password: doran1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  data:
    mongodb:
      uri: mongodb://rootuser:1234@localhost:27017/doran?authSource=admin
      authentication-database: admin

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    org.hibernate.SQL: debug

management:
  health:
    circuitbreakers:
      enabled: true

resilience4j.timelimiter:
  time-limiter-aspect-order: 3
  configs:
    default:
      timeoutDuration: 4s
  instances:
    baseTimeLimiterConfig:
      baseConfig: default

resilience4j.retry:
  retry-aspect-order: 2
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - com.sjw.doran.orderservice.exception.RetryException
      ignoreExceptions:
        - com.sjw.doran.orderservice.exception.IgnoreException
  instances:
    baseRetryConfig:
      baseConfig: default

resilience4j.circuitbreaker:
  circuit-breaker-aspect-order: 1
  configs:
    default:
      slidingWindowType: COUNT_BASED
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 40
      minimumNumberOfCalls: 7
      waitDurationInOpenState: 10s

      slowCallDurationThreshold: 3000
      slowCallRateThreshold: 60

      permittedNumberOfCallsInHalfOpenState: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

      recordExceptions:
        - com.sjw.doran.orderservice.exception.RecordException
      ignoreExceptions:
        - com.sjw.doran.orderservice.exception.IgnoreException
  instances:
    baseCircuitBreakerConfig:
      baseConfig: default

webhook:
  slack:
    url: https://hooks.slack.com/services/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