spring:
  application:
    name: order-service
  config:
    activate:
      on-profile: default
#  messages:
#    basename: errors
  datasource:
    url: jdbc:h2:tcp://localhost/~/order-database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.SQL: debug