server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/member-service/(?<segment>/*), /$\{segment}
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/**
#        - id: item-service
#          uri: lb://ITEM-SERVICE
#          predicates:
#            - Path=/item-service/**
#            - Method=GET,POST
#          filters:
#            - RewritePath=/item-service/(?<segment>/*), /$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/order-service/(?<segment>/*), /$\{segment}