server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: auth-simple-service
          uri: lb://AUTH-SIMPLE-SERVICE
          predicates:
            - Path=/auth-simple-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-simple-service/(?<segment>/*), /$\{segment}
        - id: auth-simple-service
          uri: lb://AUTH-SIMPLE-SERVICE
          predicates:
            - Path=/auth-simple-service/users
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-simple-service/(?<segment>/*), /$\{segment}
        - id: auth-simple-service
          uri: lb://AUTH-SIMPLE-SERVICE
          predicates:
            - Path=/auth-simple-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-simple-service/(?<segment>/*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET,POST
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>/*), /$\{segment}
#            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: baseCircuitBreakerConfig
                fallbackUri: forward:/fallback/member
            - name: Retry
              args:
                name: baseRetryConfig
#                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
#                backoff:
#                  firstBackoff: 1000ms
#                  maxBackoff: 2000ms
#                  factor: 2
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/item-service/(?<segment>/*), /$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/order-service/(?<segment>/*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: baseCircuitBreakerConfig
                fallbackUri: forward:/fallback/order
            - name: Retry
              args:
                name: baseRetryConfig
#                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
#                backoff:
#                  firstBackoff: 1000ms
#                  maxBackoff: 2000ms
#                  factor: 2

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - com.sjw.doran.apigatewayservice.exception.RetryException
      ignoreExceptions:
        - com.sjw.doran.apigatewayservice.exception.IgnoreException
  instances:
    baseRetryConfig:
      baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 40
      minimumNumberOfCalls: 7
      waitDurationInOpenState: 10s

      slowCallDurationThreshold: 3000
      slowCallRateThreshold: 60

      permittedNumberOfCallsInHalfOpenState: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

      recordExceptions:
        - com.sjw.doran.apigatewayservice.exception.RecordException
      ignoreExceptions:
        - com.sjw.doran.apigatewayservice.exception.IgnoreException
  instances:
    baseCircuitBreakerConfig:
      baseConfig: default