server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: auth-simple-service
          uri: lb://AUTH-SIMPLE-SERVICE
          predicates:
            - Path=/auth-simple-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-simple-service/(?<segment>/*), /$\{segment}
        - id: auth-simple-service
          uri: lb://AUTH-SIMPLE-SERVICE
          predicates:
            - Path=/auth-simple-service/users
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-simple-service/(?<segment>/*), /$\{segment}
        - id: auth-simple-service
          uri: lb://AUTH-SIMPLE-SERVICE
          predicates:
            - Path=/auth-simple-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-simple-service/(?<segment>/*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET,POST
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>/*), /$\{segment}
#            - AuthorizationHeaderFilter
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/item-service/(?<segment>/*), /$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/order-service/(?<segment>/*), /$\{segment}